### ISSUE TITLE
Can't copy directory with files via `f.files().file().save()`

### ISSUE THREAD

**Issue by maxonfjvipon** [yegor256/farea#135]
Here's a part of SnippetIT integration test from EO repository:
```java
f.files().file("src/main/eo").save(
    Paths.get(System.getProperty("user.dir")).resolve("src/main/eo")
);
```
It should copy `src/main/eo` directory with all nested files and subdirectories.

The target directory is `target/mktmp/SnippetIT/runsAllSnippets/2nd-48m17s509`.

When I go to the target directory I see that there's no EO sources inside it:
<img width="382" alt="image" src="https://github.com/user-attachments/assets/f5603b08-ebba-4291-8c4e-1fe300a96517">

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@maxonfjvipon should be fixed in a new version, please try
